# Generated by Django 2.2.3 on 2019-07-10 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pyech', '0002_auto_20190710_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfile',
            name='uploadfile',
            field=models.FileField(blank=True, upload_to='./upload/%Y/%m'),
        ),
    ]
