# Generated by Django 2.2.3 on 2019-09-19 03:33

from django.db import migrations, models
import pyech.models


class Migration(migrations.Migration):

    dependencies = [
        ('pyech', '0005_auto_20190722_0913'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customchartfile',
            options={'verbose_name': '下载文件', 'verbose_name_plural': '下载文件html'},
        ),
        migrations.AlterModelOptions(
            name='uploadfile',
            options={'verbose_name': '上传文件', 'verbose_name_plural': '上传文件csv'},
        ),
        migrations.AlterField(
            model_name='customchartfile',
            name='ChartPath',
            field=models.FileField(blank=True, storage=pyech.models.file_storage(), upload_to=pyech.models.user_chartfile_path),
        ),
        migrations.AlterField(
            model_name='uploadfile',
            name='uploadfile',
            field=models.FileField(blank=True, storage=pyech.models.file_storage(), unique=True, upload_to=pyech.models.user_directory_path),
        ),
    ]
