# Generated by Django 2.2.3 on 2019-07-10 14:12

from django.db import migrations, models
import pyech.models


class Migration(migrations.Migration):

    dependencies = [
        ('pyech', '0003_auto_20190710_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadfile',
            name='uploadfile',
            field=models.FileField(blank=True, upload_to=pyech.models.user_directory_path),
        ),
    ]
